package interview.prep.dailybyte;
/*
This question is asked by Google. You are given two strings, s and t which only consist of lowercase letters.
t is generated by shuffling the letters in s as well as potentially adding an additional random character.
 Return the letter that was randomly added to t if it exists, otherwise, return ’ ‘.
Note: You may assume that at most one additional character can be added to t.

389. Find the Difference
Easy

1220

313

Add to List

Share
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
Example 3:

Input: s = "a", t = "aa"
Output: "a"
Example 4:

Input: s = "ae", t = "aea"
Output: "a"
 */
public class SpotDifference {
    public char findTheDifference(String s, String t) {
        if(s.isEmpty())
            return t.charAt(0);

        int[] freq = new int[26];
        for(char c: s.toCharArray())
            freq[c-'a']++;

        for(char c: t.toCharArray())
            freq[c-'a']--;

        for(int i=0; i<freq.length;i++){
            if(freq[i]!=0)
                return (char)(i+'a');
        }
        return ' ';
    }
}
